PGManager/Areas/Admin/Controllers/CitiesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PGManager.DataAccess.Repository.IRepository;
using PGManager.Models;
using PGManager.Utilities;

namespace PGManager.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CitiesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CitiesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var cities = await _unitOfWork.City.GetAllAsync();
            cities = cities.OrderBy(c => c.Name);
            return View(cities);
        }

        [HttpGet]
        public async Task<IActionResult> Upsert(int? id)
        {
            City city;
            if (id == null || id == 0)
                city = new City();
            else
                city = await _unitOfWork.City.GetAsync(id.GetValueOrDefault());

            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(City city)
        {
            if (ModelState.IsValid)
            {
                if (city.Id == 0)
                    await _unitOfWork.City.AddAsync(city);
                else
                {
                    var cityFromDB = await _unitOfWork.City.GetAsync(city.Id);
                    if (cityFromDB == null)
                        await _unitOfWork.City.AddAsync(city);
                    else
                    {
                        await _unitOfWork.City.Update(city);
                    }
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(city);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            await _unitOfWork.City.RemoveAsync(id);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }
    }
}

PGManager/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PGManager.DataAccess.Data;
using PGManager.DataAccess.Repository.IRepository;
using PGManager.Models;
using PGManager.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace PGManager.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDbContext _db;

        public UserController(IUnitOfWork unitOfWork, ApplicationDbContext db)
        {
            _unitOfWork = unitOfWork;
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }



        #region API CALLS

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var userList = await _unitOfWork.ApplicationUser.GetAllAsync();
            var userRole = await _db.UserRoles.ToListAsync();
            var roles = await _db.Roles.ToListAsync();
            foreach(var user in userList)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
            }

            return Json(new { data = userList });
        }

      [HttpPost]
      public IActionResult LockUnlock([FromBody] string id)
        {
            var objFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while Locking/Unlocking" });
            }
            if(objFromDb.LockoutEnd!=null && objFromDb.LockoutEnd > DateTime.Now)
            {
                //user is currently locked, we will unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
           _db.SaveChanges();
            return Json(new { success = true, message = "Operation Successful." });
        }

        #endregion
    }
}

PGManager/Areas/Owner/Controllers/PGController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PGManager.DataAccess.Repository.IRepository;
using PGManager.Models;
using PGManager.Models.ViewModels;
using PGManager.Utilities;

namespace PGManager.Areas.Owner.Controllers
{
    [Area("Owner")]
    [Authorize(Roles = SD.Role_User_Owner)]
    public class PGController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PGController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            PG pg;
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            pg = await _unitOfWork.PG.GetAsync(claim.Value, true, true, false);

            if (pg == null)
            {
                pg = new PG();
            }

            return View(pg);
        }

        [HttpGet]
        public async Task<IActionResult> Upsert()
        {
            PGEditViewModel pgEdit = new PGEditViewModel();
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            pgEdit.PG = await _unitOfWork.PG.GetAsync(claim.Value, true, true, false);


            if (pgEdit.PG == null)
            {
                pgEdit.PG = new PG();
                var facilities = await _unitOfWork.Facility.GetAllAsync();
                pgEdit.Facilities = facilities.ToList();
            }
            else
            {
                var facilities = await _unitOfWork.PG.GetFacilitiesForPG(pgEdit.PG.Id);
                pgEdit.Facilities = facilities.ToList();
            }

            IEnumerable<City> cities = await _unitOfWork.City.GetAllAsync();

            ViewBag.CityList = cities.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = c.Id.ToString()
            }).ToList();

            return View(pgEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert([FromForm] PGEditViewModel pgVM)
        {
            PGEditViewModel pgEdit = new PGEditViewModel();
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            PG pg = pgVM.PG;
            pg.ApplicationUserId = claim.Value;
            if (!pg.IsMale && !pg.IsFemale)
            {
                pg.IsMale = true;
            }

            await _unitOfWork.PG.Update(pg, pgVM.Facilities);

            return RedirectToAction(nameof(Index));
        }
    }
}

PGManager/Areas/Owner/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PGManager.DataAccess.Repository.IRepository;
using PGManager.Models;
using PGManager.Utilities;

namespace PGManager.Areas.Owner.Controllers
{
	[Area("Owner")]
	[Authorize(Roles = SD.Role_User_Owner)]
	public class RoomsController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

		public RoomsController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			PG pg;
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			pg = await _unitOfWork.PG.GetAsync(claim.Value, IncludeRooms: true);

			return View(pg.Rooms);
		}

		[HttpGet]
		public async Task<IActionResult> Upsert(int id)
		{
			Room room;
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			PG pg = await _unitOfWork.PG.GetAsync(claim.Value, IncludePriceTiers: true);

			IList<SelectListItem> tiers = pg.PriceTiers.Select(pt => new SelectListItem()
			{
				Text = $"{pt.Name} (₹{String.Format("{0:n2}", pt.Rent)})",
				Value = pt.Id.ToString()
			}).ToList();

			ViewBag.Tiers = tiers;
			ViewBag.Male = pg.IsMale;
			ViewBag.Female = pg.IsFemale;

			if (id == 0)
				room = new Room();
			else
				room = await _unitOfWork.Room.GetAsync(id);

			return View(room);
		}

		[HttpPost]
		public async Task<IActionResult> Upsert(Room room)
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			PG pg = await _unitOfWork.PG.GetAsync(claim.Value, IncludePriceTiers: true);

			if (ModelState.IsValid)
			{

				if (pg.PriceTiers.Any(pt => pt.Id == room.PriceTierId))
				{
					if (room.Id == 0)
					{
						room.PGId = pg.Id;
						await _unitOfWork.Room.AddAsync(room);
					}
					else
					{
						await _unitOfWork.Room.UpdateAsync(room);
					}
					_unitOfWork.Save();
				}
				else
				{
					IList<SelectListItem> tiers = pg.PriceTiers.Select(pt => new SelectListItem()
					{
						Text = $"{pt.Name} (₹{String.Format("{0:n2}", pt.Rent)})",
						Value = pt.Id.ToString()
					}).ToList();

					ViewBag.Tiers = tiers;
					ViewBag.Male = pg.IsMale;
					ViewBag.Female = pg.IsFemale;

					return View(room);
				}
			}
			else
			{
				IList<SelectListItem> tiers = pg.PriceTiers.Select(pt => new SelectListItem()
				{
					Text = $"{pt.Name} (₹{String.Format("{0:n2}", pt.Rent)})",
					Value = pt.Id.ToString()
				}).ToList();

				ViewBag.Tiers = tiers;
				ViewBag.Male = pg.IsMale;
				ViewBag.Female = pg.IsFemale;

				return View(room);
			}

			return RedirectToAction(nameof(Index));
		}

		[HttpGet]
		public async Task<IActionResult> EditBed(int id, int roomId)
		{
			Bed bed;
			if (id == 0)
			{
				bed = new Bed()
				{
					RoomId = roomId
				};
			}
			else
			{
				bed = await _unitOfWork.Bed.GetAsync(id);
			}

			return View(bed);
		}

		[HttpPost]
		public async Task<IActionResult> EditBed(Bed bed)
		{
			if (ModelState.IsValid)
			{
				if (bed.Id == 0)
					await _unitOfWork.Bed.AddAsync(bed);
				else
					await _unitOfWork.Bed.UpdateAsync(bed);
				_unitOfWork.Save();

				return RedirectToAction(nameof(Details), new { id = bed.RoomId });
			}
			else
				return View(bed);

		}

		[HttpGet]
		public async Task<IActionResult> Details(int id)
		{
			Room room = await _unitOfWork.Room.GetAsync((r => r.Id == id), includeProperties: "PriceTier,Beds");

			return View(room);
		}

		[HttpGet]
		public async Task<IActionResult> StayHistory(int id)
		{
			if (id == 0)
				return RedirectToAction(nameof(Index));

			var bed = await _unitOfWork.Bed.GetAsync(bed => bed.Id == id, includeProperties: "Room.PG");

			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (bed == null || bed.Room.PG.ApplicationUserId != claim.Value)
				return RedirectToAction(nameof(Index));

			var stays = await _unitOfWork.Stay.GetAllAsync(stay => stay.BedId == bed.Id,
															includeProperties: "Room,Bed,PG,Tenant",
															orderBy: stay => stay.OrderByDescending(s => s.StartDate));

			return View(stays);
		}

	}
}

PGManager/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index"  class="btn btn-success form-control">Back to List</a>
    </div>
</div>

PGManager/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index"  class="btn btn-success form-control">Back to List</a>
    </div>
</div>

PGManager/Views/Shared/_Layout.cshtml
@using PGManager.Utilities
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PGManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Tenant" asp-controller="Home" asp-action="Index"><img src="~/favicon.ico" style="width:30px" class="mr-1" />PGManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex ">
                    <ul class="navbar-nav mr-auto">
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Masters
                                </a>
                                <div class="dropdown-menu bg-dark mt-2" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-light" asp-area="Admin" asp-controller="Cities" asp-action="Index">City</a>
                                    <a class="dropdown-item text-light" asp-area="Admin" asp-controller="Facilities" asp-action="Index">Facility</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_User_Owner))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Owner" asp-controller="PG" asp-action="Index">PG Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Owner" asp-controller="Photos" asp-action="Index">Photos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Owner" asp-controller="PriceTier" asp-action="Index">Price Tiers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Owner" asp-controller="Rooms" asp-action="Index">Rooms</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Owner" asp-controller="Request" asp-action="Index">Requests</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_User_Customer))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Tenant" asp-controller="PG" asp-action="Index">Find PG</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Tenant" asp-controller="PG" asp-action="MyStays">My Stays</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Tenant" asp-controller="Documents" asp-action="Index">My Documents</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3 ml-5 mr-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light bg-dark">
        <div class="container-fluid">
            &copy; 2020 - PGManager - <a class="text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/a2ce765c65.js" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    @RenderSection("Scripts", required: false)
    @RenderSection("Styles", required: false)
</body>
</html>

PGManager/Views/Shared/_PGRequestList.cshtml
@model IEnumerable<PGManager.Models.PGRequest>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                Applicant
            </th>
            <th>
                Request On
            </th>
            <th>
                Price Tier
            </th>
            <th>
                Status
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Applicant.Name
                    </td>
                    <td>
                        @item.RequestOn.ToString("dd-MMM-yyyy")
                    </td>
                    <td>
                        @item.PriceTier.Name
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RequestStatus)
                    </td>
                    <td>
                        @item.Date.ToString("dd-MMM-yyyy")
                    </td>
                    <td>
                        <a asp-action="UserDetails" asp-controller="Request" asp-area="Owner" asp-route-id="@item.ApplicantUserId" class="btn btn-primary btn-sm" style="cursor:pointer;" title="Applicant Details">
                            <i class="fas fa-user"></i>
                        </a>
                        <a asp-action="Approve" asp-controller="Request" asp-area="Owner" asp-route-id="@item.Id" class="btn btn-primary btn-sm" style="cursor:pointer;" title="Approve/Reject">
                            <i class="fas fa-check"></i>&nbsp;<i class="fas fa-times"></i>
                        </a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6" style="text-align:center;">No Records Available!</td>
            </tr>
        }
    </tbody>
</table>