PGManager/Areas/Owner/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using PGManager.DataAccess.Repository.IRepository;
using PGManager.Models;
using PGManager.Models.Enums;
using PGManager.Models.ViewModels;
using PGManager.Utilities;

namespace PGManager.Areas.Owner.Controllers
{
	[Area("Owner")]
	[Authorize(Roles = SD.Role_User_Owner)]
	public class RequestController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

		#region Constructor
		public RequestController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}
		#endregion

		#region Actions
		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			PG pg = await _unitOfWork.PG.GetAsync(claim.Value);

			var requests = await _unitOfWork.PGRequest.GetAllAsync(req => req.PGId == pg.Id && req.RequestStatus == RequestStatus.Pending,
																	includeProperties: "Applicant,PriceTier",
																	orderBy: x => x.OrderByDescending(req => req.Date));

			return View(requests);
		}

		[HttpGet]
		public async Task<IActionResult> UserDetails(string id)
		{
			var user = await _unitOfWork.ApplicationUser.GetAsync(u => u.Id == id, includeProperties: "Documents");
			if (user == null)
			{
				user = new ApplicationUser();
			}

			return View(user);
		}

		[HttpGet]
		public async Task<IActionResult> Approve(int id)
		{
			PGRequestViewModel requestVM = new PGRequestViewModel();
			requestVM.Request = await _unitOfWork.PGRequest.GetAsync(req => req.Id == id, includeProperties: "PG,PriceTier,Applicant");

			var rooms = await _unitOfWork.Room.GetAllAsync(room => room.PriceTierId == requestVM.Request.PriceTierId);


			IList<SelectListItem> roomList = rooms.Select(r => new SelectListItem()
			{
				Text = r.RoomNumber,
				Value = r.Id.ToString()
			}).ToList();

			ViewBag.RoomList = roomList;

			return View(requestVM);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Approve(PGRequestViewModel requestVM)
		{
			requestVM.Request = await _unitOfWork.PGRequest.GetAsync(requestVM.Request.Id);

			if (requestVM.Action == "A" && requestVM.Request.RequestType == RequestType.Join)
			{
				if (requestVM.RoomId == null || requestVM.RoomId == 0)
					ModelState.AddModelError("RoomId", "Please Select Room");
				if (requestVM.BedId == null || requestVM.BedId == 0)
					ModelState.AddModelError("BedId", "Please Select Bed");
			}
			if (ModelState.IsValid)
			{

				if (requestVM.Action == "A")
				{
					if (requestVM.Request.RequestType == RequestType.Join)
					{
						PG pg = await _unitOfWork.PG.GetAsync(pg => pg.Id == requestVM.Request.PGId, includeProperties: "Rooms.Beds");
						var room = pg.Rooms.Where(room => room.Id == requestVM.RoomId).SingleOrDefault();
						if (room != null)
						{
							var bed = room.Beds.Where(bed => bed.Id == requestVM.BedId).SingleOrDefault();
							if (bed != null)
							{
								await _unitOfWork.Stay.StartStay(requestVM.Request, room.Id, bed.Id);
								bed.JoinDate = requestVM.Request.Date;
							}
							else
								ModelState.AddModelError("BedId", "Invalid Bed");
						}
						else
							ModelState.AddModelError("RoomId", "Invalid Room");
					}
					else if (requestVM.Request.RequestType == RequestType.Leave)
					{
						if (requestVM.Request.StayId == null)
							ModelState.AddModelError("", "Invalid Request");
						else
							await _unitOfWork.Stay.EndStay(requestVM.Request);
					}
				}
				else
				{
					requestVM.Request.LastActionOn = DateTime.Now;
					requestVM.Request.RequestStatus = RequestStatus.Rejected;
				}
				if (ModelState.IsValid)
				{
					_unitOfWork.Save();
					return RedirectToAction(nameof(Index));
				}
			}

			requestVM.Request = await _unitOfWork.PGRequest.GetAsync(req => req.Id == requestVM.Request.Id, includeProperties: "PG,PriceTier,Applicant");

			var rooms = await _unitOfWork.Room.GetAllAsync(room => room.PriceTierId == requestVM.Request.PriceTierId);

			IList<SelectListItem> roomList = rooms.Select(r => new SelectListItem()
			{
				Text = r.RoomNumber,
				Value = r.Id.ToString()
			}).ToList();

			ViewBag.RoomList = roomList;

			return View(requestVM);
		}

		[HttpGet]
		public async Task<JsonResult> GetBeds(int id)
		{
			var beds = await _unitOfWork.Bed.GetAllAsync(bed => bed.RoomId == id);

			beds = beds.Where(bed => !bed.Occupied).ToList();

			return Json(beds);
		}
		#endregion
	}
}

PGManager/Areas/Owner/Views/Request/Approve.cshtml
@model PGManager.Models.ViewModels.PGRequestViewModel

@{
	ViewData["Title"] = "Approve Request";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{
	<style>
		.ApproveSection {
			display: none;
		}
	</style>
}

<div class="row">
	<div class="col-12 border-bottom">
		<h2 class="text-primary">Approve</h2>
	</div>
	<div class="col-md-8 mt-3">
		<form asp-action="Approve" method="post">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input asp-for="Request.Id" type="hidden" />
			<input asp-for="Request.RequestType" type="hidden" />
			<div class="row">
				<div class="col-md-12">
					<div class="row">
						<div class="col-sm-3 mt-1 mb-1">
							<label asp-for="Request.RequestType" class="control-label font-weight-bold"></label>
						</div>
						<div class="col-sm-9 mt-1 mb-1">
							@Model.Request.RequestType
						</div>
						<div class="col-sm-3 mt-1 mb-1">
							<label asp-for="Request.RequestStatus" class="control-label font-weight-bold"></label>
						</div>
						<div class="col-sm-9 mt-1 mb-1">
							@Model.Request.RequestStatus
						</div>
						<div class="col-sm-3 mt-1 mb-1">
							<label asp-for="Request.Date" class="control-label font-weight-bold"></label>
						</div>
						<div class="col-sm-9 mt-1 mb-1">
							@Model.Request.Date.ToString("dd-MMM-yyyy")
						</div>
						<div class="col-sm-3 mt-1 mb-1">
							<label asp-for="Request.RequestOn" class="control-label font-weight-bold"></label>
						</div>
						<div class="col-sm-9 mt-1 mb-1">
							@Model.Request.RequestOn.ToString("dd-MMM-yyyy")
						</div>
						<div class="col-sm-3 mt-1 mb-1">
							<label asp-for="Request.Description" class="control-label font-weight-bold"></label>
						</div>
						<div class="col-sm-9 mt-1 mb-1">
							@Model.Request.Description
						</div>
						<div class="col-sm-3 mt-1 mb-1">
							<label class="control-label font-weight-bold">Applicant</label>
						</div>
						<div class="col-sm-9 mt-1 mb-1">
							<a asp-action="UserDetails" asp-controller="Request" asp-area="Owner" asp-route-id="@Model.Request.ApplicantUserId" target="_blank" style="cursor:pointer;" title="Applicant Details">
								@Model.Request.Applicant.Name
							</a>
						</div>
						<div class="col-sm-3 mt-1 mb-1">
							<label asp-for="Action" class="control-label font-weight-bold"></label>
						</div>
						<div class="col-sm-9 mt-1 mb-1">
							<select asp-for="Action" class="form-control col-md-4">
								<option value="" selected>Select Action</option>
								<option value="A">Accept</option>
								<option value="R">Reject</option>
							</select>
							<span asp-validation-for="Action" class="text-danger"></span>
						</div>
						<div class="col-sm-3 mt-1 mb-1 ApproveSection">
							<label asp-for="RoomId" class="control-label font-weight-bold"></label>
						</div>
						<div class="col-sm-9 mt-1 mb-1 ApproveSection">
							@Html.DropDownListFor(m => m.RoomId, (IEnumerable<SelectListItem>)ViewBag.RoomList, "Select Room", new { @class = "form-control col-md-4" })
							<span asp-validation-for="RoomId" class="text-danger"></span>
						</div>
						<div class="col-sm-3 mt-1 mb-1 ApproveSection">
							<label asp-for="BedId" class="control-label font-weight-bold"></label>
						</div>
						<div class="col-sm-9 mt-1 mb-1 ApproveSection">
							<select asp-for="BedId" class="form-control col-md-4" disabled>
							</select>
							<span asp-validation-for="BedId" class="text-danger"></span>
						</div>
					</div>
				</div>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-success" id="BtnSave" disabled />
				<a type="button" asp-action="Index" class="btn btn-danger">Cancel</a>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

	<script>
        $(document).ready(function () {
            $('#BedId').find('option').remove().end().append('<option value="" selected>Select Bed</option>').val('');
            var requestType = '@Model.Request.RequestType';
            if ($('#Action').val() != '') {
                $('#BtnSave').prop('disabled', false);
				if ($('#Action').val() == "A") {
					if (requestType=='Join')
						$('.ApproveSection').show();
                    $('#BtnSave').val('Approve');
                }
                else {
                    $('.ApproveSection').hide();
                    $('#BtnSave').val('Reject');
                }
            }

            if ($('#RoomId').val() != '') {
                GetBeds($('#RoomId').val());
                $('#BedId').prop('disabled', false);
            }

            var roomId = $('#RoomId').val();
            if (roomId != null && roomId != '' & !isNaN(roomId)) {
                GetBeds(roomId);
            }

            $('#Action').change(function () {
                var ddlValue = $(this).val();
                if (ddlValue == null || ddlValue == '') {
                    $('#BtnSave').prop('disabled', true);
                    $('#BtnSave').val('Save');
                    $('.ApproveSection').hide(300);
                }
                else {
                    $('#BtnSave').prop('disabled', false);
					if (ddlValue == "A") {
						if (requestType == 'Join')
							$('.ApproveSection').show(300);
                        $('#BtnSave').val('Approve');
                    }
                    else {
                        $('.ApproveSection').hide(300);
                        $('#BtnSave').val('Reject');
                    }
                }
            });

            $('#RoomId').change(function () {
                var ddlValue = $(this).val();
                $('#BedId').prop('disabled', true);
                if (ddlValue != null && ddlValue != '') {
                    $('#BedId').prop('disabled', false);
                    GetBeds(ddlValue);
                }
                else {
                    $('#BedId').find('option').remove().end().append('<option value="" selected>Select Bed</option>').val('');
                }
            });

            function GetBeds(roomId) {
                var url = window.location.origin + '@Url.Action("GetBeds", "Request",new { Area="Owner"})' ;
                var Beds = $("#BedId");
                $.getJSON(url, { id: roomId }, function (response) {
                    Beds.empty().append($('<option></option>').val('').text('Select Bed'));
                    $.each(response, function (index, item) {
                        Beds.append($('<option></option>').val(item.id).text(item.bedNo));
                    });
                });
            }
        });
	</script>
}

PGManager/Areas/Owner/Views/Request/Index.cshtml
@model IEnumerable<PGManager.Models.PGRequest>
@using PGManager.Models.Enums;

@{
    ViewData["Title"] = "Requests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Requests</h2>
<br />
<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-join-tab" data-toggle="tab" href="#nav-join" role="tab" aria-controls="nav-home" aria-selected="true">Join Requests</a>
        <a class="nav-item nav-link" id="nav-leave-tab" data-toggle="tab" href="#nav-leave" role="tab" aria-controls="nav-profile" aria-selected="false">Leave Requests</a>
    </div>
</nav>
<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-join" role="tabpanel" aria-labelledby="nav-join-tab">
        <partial name="_PGRequestList" model="Model.Where(req=>req.RequestType==RequestType.Join).ToList()" />
    </div>
    <div class="tab-pane fade" id="nav-leave" role="tabpanel" aria-labelledby="nav-leave-tab">
        <partial name="_PGRequestList" model="Model.Where(req=>req.RequestType==RequestType.Leave).ToList()" />
    </div>
</div>

PGManager/Areas/Owner/Views/Request/UserDetails.cshtml
@model PGManager.Models.ApplicationUser
@{
	ViewData["Title"] = "User Details";
}
<div class="row">
	<div class="col-md-6">
		<dl class="row">
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Name)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Name)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.StreetAddress)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.StreetAddress)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.City)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.City)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.State)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.State)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Email)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Email)
				&nbsp;
				@if (Model.EmailConfirmed)
				{
					<span class="btn btn-outline-light btn-sm text-dark"><i class="fa fa-check-circle" style="color:green;"></i>&nbsp;Verified</span>
				}
				else
				{
					<span class="btn btn-outline-light btn-sm text-dark"><i class="fa fa-times-circle" style="color:red;"></i>&nbsp;Unverified</span>
				}
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayName("Phone Number")
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.PhoneNumber)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Gender)
			</dt>
			<dd class="col-sm-10">
				@if (Model.Gender == 'M')
				{
					<span class="btn btn-outline-light btn-sm text-dark"><i class="fa fa-male" style="color:royalblue;"></i>&nbsp;Male</span>
				}
				@if (Model.Gender == 'F')
				{
					<span class="btn btn-outline-light btn-sm text-dark"><i class="fa fa-female" style="color:hotpink;"></i>&nbsp;Female </span>
				}
			</dd>
		</dl>
	</div>
	<div class="col-md-6">
		<h4 class="mb-3 text-info">Documents</h4>
		<div class="row">
			@if (Model.Documents.Any())
			{
				foreach (var doc in Model.Documents)
				{
					<div class="col-md-6">
						<img class="d-block w-100" src="@doc.Url" alt="No Photos Available" style="max-height:200px;" />
					</div>
				}
			}
			else
			{
				<span>No documents available.</span>
			}
		</div>
	</div>
</div>